version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dockers/postgres/restore:/restore
      - ./dockers/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=password    
    networks:
      - django_network

  backend:
    container_name: backend
    image: backend
    build:
      context: .
      dockerfile:  ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
    restart: always
    depends_on:
      - postgres
      - redis
    networks:
      - django_network
    command: 
      - gunicorn
      - --bind
      - 0:8000
      - --reload
      - config.wsgi:application

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./dockers/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - django_network
    restart: always  

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - django_network


    


networks:
  django_network:

volumes:
  postgres_data: